### PR TITLE
Checking if folder is here

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
@mosteo Looks like msys2 is not installed in the correct location.

**Comment by Fabien-Chouteau** [comment]
Well.. https://github.com/msys2/msys2-installer/pull/20

**Comment by mosteo** [comment]
Well spotted... Urgh, I had just found the new install location via https://github.com/mosteo/alire/pull/11 but couldn't figure how that could be happening. Thanks!

**Comment by Fabien-Chouteau** [comment]
Unfortunately that means all `0.7.x` versions of `alr` are broken.

**Comment by mosteo** [comment]
After the pending merges I think we are ready to branch out `releases/1.x`

**Pull request closed without merging**
