### PR TITLE
Fix for link cycle detection

### PR DESCRIPTION
**Pull request by mosteo**

### CODE REVIEW

**Comment by mosteo** [comment]
@onox , if you can try with this one for your latest report...

**Comment by onox** [comment]
@mosteo I get a compile error:

```
   [Ada]          alire-types.ads
alire-roots.adb:375:30: "Sol" is undefined
alire-roots.adb:417:23: "Sol" is undefined
alire-roots.adb:418:19: "Sol" is undefined
alire-roots.adb:418:26: "Sol" is undefined
alire-roots.adb:425:16: "Sol" is undefined
alire-roots.adb:425:23: "Sol" is undefined
alire-roots.adb:469:47: "Sol" is undefined
alire-roots.adb:640:06: no value supplied for component "Pins_Direct"
alire-roots.adb:640:06: no value supplied for component "Pins_Closure"

   compilation of alire-roots.adb failed
```

**Comment by onox** [comment]
Oh, I need to refetch the branch, stand by...

**Comment by onox** [comment]
@mosteo All good! :ok_hand: I can build wayland-ada, orka, and awt.

**Review by Fabien-Chouteau — APPROVED** [review]

**Comment by mosteo** [comment]
> @mosteo All good!  I can build wayland-ada, orka, and awt.

Great, thanks!

**Comment by onox** [comment]
@mosteo Thank you for your work on the pins :smile:

**Pull request merged**
