### PR TITLE
Prefer usage of quantified expressions

### PR DESCRIPTION
**Pull request by pjljvandelaar**
Addresses [issue 1237](https://github.com/alire-project/alire/issues/1237)

Solution by Rejuvenation-Ada crate
[vote for Rejuvenation-Ada as The 2022 Ada Crate Of The Year](https://github.com/AdaCore/Ada-SPARK-Crate-Of-The-Year/issues/15)

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
Don't understand why the macos-latest fails.
Could you please explain if I did something wrong.

**Comment by mosteo** [comment]
macOS errors are not caused by your changes, we're investigating this issue.

**Comment by jquorning** [comment]
macOS: *The logs for this run have expired and are no longer available.*

**Review by jquorning — COMMENTED** [review]
This program text is working only with an *Ada 2012* compiler.

**Comment by pjljvandelaar** [comment]
> This program text is working only with an _Ada 2012_ compiler.

Indeed, quantified expressions are supported since Ada 2012.
See e.g. https://www.adacore.com/uploads/technical-papers/Ada2012_Rationale_Chp2_expressions.pdf

**Review by mosteo — APPROVED** [review]

**Pull request merged**
