### PR TITLE
Externals 2/4: command-line tools

### PR DESCRIPTION
**Pull request by mosteo**
This implements detection of version from strings emitted by an executable in the env path. Currently, this serves to fix the make and gnat crates.

In regard to the gnat crate, this improves the situation of the growing compiler enumeration in that now the compiler is a normal dependency, so the compiler version environment variable is gone (see e.g. [gnatcoll.toml](https://github.com/mosteo/alire-index/blob/5e2cccdf3a0f8bcd0d7ad5a87bd4f30e3e4657aa/index/gn/gnatcoll.toml#L49)). It still does not use gprconfig to detect runtimes/targets. That is an issue at another level for which I don't have a clear idea yet.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
What I find interesting with this is that we will be able to declare dependencies on cross compilers:

`riscv32_elf_gnat.toml` or `gnat_riscv32_elf.toml`:
```
[...]
[[external]]
kind = "output-version"
version-command = [ "riscv32-gnat", "--version" ]
version-regexp = "^GNAT ([\\d\\.]+).*|^GNAT Community ([\\d]{4}).*"
```

**Comment by mosteo** [comment]
Yup. I was thinking however how would we like to do with a crate available for several targets. I guess you will have better ideas than me about this:

- individual releases per target, each depending on the concrete cross-gnat. The build string of versions could fit the bill here: "1.0+native", "1.0+riscv32", and so on.
- a way to express alternative dependencies, so a single release may depend on any of several gnat_* crates (related to #106).
- ...

**Comment by mosteo** [comment]
Indeed I just saw that your latest crates for the index have a list of project files, which I guess only one can be used, for each appropriate target.

**Comment by Fabien-Chouteau** [comment]
I think almost all library crates will be cross-platform, the real question will be run-time profile.

The bin/app crates will have a fixed set of boards/targets they can be compiled for, so a fixed list of compiler dependency.

**Pull request merged**
