### PR TITLE
Alire.Crate_Configuration: add built-in values for host OS, Arch and Distro

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
```
stderr: Command ["pacman", "-V"] exited with code-1 and output:
```
Msys2's pacman is being annoying. This is a good time to investigate how to improve that part of Alire...

**Review by mosteo — APPROVED** [review]
Looks good to me, once tests pass.

**Comment by Fabien-Chouteau** [comment]
@mosteo fixed now. I had to change the Windows `Platforms` code again :man_shrugging:

**Comment by mosteo** [comment]
I see, thanks Fabien.

**Pull request merged**
