### PR TITLE
Remove VCS origins

### PR DESCRIPTION
**Pull request by mosteo**
Those were deprecated in favor of only source archives. This is a cleanup of the now unused code.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
I don't think agree with this one. Maybe I should read the discussion again, but git origin seems like a useful feature for local indexes.

**Comment by Fabien-Chouteau** [comment]
Provided we can test it.

**Comment by mosteo** [comment]
No objection from me. We might then enforce that those must be local? All the issue stems that we didn't find an easy way of checking the integrity of this kind of remotes.

A separate issue would be if we want to keep hg/svn too.

> Provided we can test it.

In the ultimately dropped #198 there were local tests using local repos, IIRC.

**Comment by Fabien-Chouteau** [comment]
> We might then enforce that those must be local?

Yes, forbid them in the community index with a check.

**Pull request closed without merging**
