### PR TITLE
Implement sha256 and hash use test

### PR DESCRIPTION
**Pull request by mosteo**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hi Alejandro, why do we need sha256?

**Comment by mosteo** [comment]
I saw this was the hash generated for the GNAT releases at https://github.com/alire-project/GNAT-FSF-builds/releases/tag/gnat-10.3.0-1

We could compute the sha512, of course. I just thought that it made sense to use the same hash that's provided by the build process.

**Comment by Fabien-Chouteau** [comment]
Since sha512 is our standard for crates I should also use that for the GNAT FSF packages.

**Comment by mosteo** [comment]
OK, I'm going to keep this one around for a while for my tests, and I'll remove it before the final merge.

**Comment by mosteo** [comment]
Merged into temporary branch.

**Pull request merged**
