### PR TITLE
Update msys installer to latest stable release

### PR DESCRIPTION
**Pull request by mosteo**
Let's see if this fixes the CI problem.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
It looks like the new installer doesn't need an external script for command line installation.
I will have a look at this.

**Comment by Fabien-Chouteau** [comment]
@mosteo We should be good now

**Comment by mosteo** [comment]
That's great, thanks @Fabien-Chouteau . I guess we should do a patch update for the stable release?

**Comment by Fabien-Chouteau** [comment]
> I guess we should do a patch update for the stable release?

Yes that's a good idea.

**Pull request merged**
