### PR TITLE
Build switches: unconditionally add -gnatW8

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
CC @reznikmm

### CODE REVIEW

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
I'm in favor of all things Unicode/UTF-8. I do remember however some discussions about this on c.l.a. about things not working out so seamlessly. 

See https://groups.google.com/g/comp.lang.ada/c/l0aflBePm_E/m/BUtW96RhAgAJ and following discussion.

I'm leaving this here before merging for a while just in case, with the idea of merging it for the next release if we found no objection. I admit to having no experience with the issue.

**Comment by Fabien-Chouteau** [comment]
After some further discussion, the risk of introducing incompatibilities is too high to make this the default switch.

**Comment by reznikmm** [comment]
> After some further discussion, the risk of introducing incompatibilities is too high to make this the default switch.

Could you elaborate? What incompatibilities did you find?

I've compiled these two files and got exactly assembler output:

```ada
package Pkg is
   ["03C0"] : Integer;
end Pkg;
```

    gcc -S pkg.ads
    mv pkg.s pkg.s_

```ada
package Pkg is
   π : Integer;
end Pkg;
```

    gcc -S -gnatW8 -gnatwi pkg.ads
    diff -u pkg.s pkg.s_

**Comment by Fabien-Chouteau** [comment]
`-gnatW8` tells GNAT to decode sources as UTF-8 for the sources to compile, but also all their dependencies, so when building crate A, this will also affect the processing of the dependency crate B

**Review by mosteo — APPROVED** [review]

**Pull request merged**
