### PR TITLE
Update msys2 installer

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
It's the `pacman -Su`  command that is causing trouble. I don't know why yet and how to fix it.
https://github.com/alire-project/alire/blob/a5aa0e399b5d790c7cdc37e21b7c7f4d84e68b4f/src/alire/os_windows/alire-platforms-current__windows.adb#L330

Since there's also this problem with `1.2.1` we might have to publish a fix release.

**Comment by mosteo** [comment]
This is vexing because IIRC I added that second update precisely to survive some other msys2 problems. Oh well.

**Comment by mosteo** [comment]
I think I've got the solution. Push incoming.

**Comment by mosteo** [comment]
The remaining failure is because the self-build is done with the latest release, which doesn't contain the fix. So I think we're good to go.

**Comment by mosteo** [comment]
@Fabien-Chouteau, for some reason I cannot add you directly as reviewer. If you can take a look at the PR, thanks!

**Comment by Fabien-Chouteau** [comment]
Because I am the author of the PR. Also I can't approve the PR.

**Comment by mosteo** [comment]
Oh right...

**Review by mosteo — APPROVED** [review]

**Pull request merged**
