### PR TITLE
Do not allow VCS origins in the community index

### LINKED ISSUE #272: Restrict VCS origins to local repositories
Per #269.

With matching tests.

### PR DESCRIPTION
**Pull request by mosteo**
Fixes #272

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Sorry @mosteo, that's not what I had in mind when I said local indexes.

I think remote or local VCS sources should be allowed for custom/local indexes, but forbidden for the official community index.

**Comment by mosteo** [comment]
Ahhh ok. Shouldn't be much trouble either.

**Comment by Fabien-Chouteau** [comment]
I would rather implement this as a check in the `alire-index` repo.

**Comment by mosteo** [comment]
Yup, more sensible.

**Comment by mosteo** [comment]
Closing, to be implemented in the alire-index checking actions.

**Pull request closed without merging**
