### PR TITLE
[RFC] Replace `'...'` with `others` in manifest files

### PR DESCRIPTION
**Pull request by mosteo**
In the context of manifest refactorings this one popped into my head. I know we are not striving anymore to copy Ada syntax in the index, but I wonder if it would be more intuitive to use `others` instead of `'...'` for case expressions in toml manifests. The reasons: familiar to Adaists, it avoids the problem of forgetting quotes, it does not use a symbol that has a different meaning (ranges) in Ada.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
There is a risk of `others` being a value of the case that users want to match.

**Comment by mosteo** [comment]
We are the ones defining values for these environment enums, so in principle we could always avoid the clash.

**Comment by Fabien-Chouteau** [comment]
I don't know, we might want to match on more stuff in the future.

If we say that this is pure string matching then we can allow regex and `...` becomes `.*`.

**Comment by mosteo** [comment]
OK, if this isn't a clear change let's keep it as it is.

**Pull request closed without merging**
