### PR TITLE
Emit error for all unset configuration variables

### PR DESCRIPTION
**Pull request by jquorning**
Improve user experience by emitting error for each unset configuration variable.

Output of `alr get lvgl_ada`:
```
error: Configuration variable 'lvgl_ada.density_per_inch' not set and has no default value.
error: Configuration variable 'lvgl_ada.pixel_bit_depth' not set and has no default value.
error: Configuration variable 'lvgl_ada.horizontal_resolution' not set and has no default value.
error: Configuration variable 'lvgl_ada.vertical_resolution' not set and has no default value.
error: Configuration failed
```
Before:
```
error: Configuration variable 'lvgl_ada.density_per_inch not set and has no default value.
```

### CODE REVIEW

**Review by Fabien-Chouteau — APPROVED** [review]
Looks good to me. Thanks @jquorning

**Comment by Fabien-Chouteau** [comment]
@jquorning you might want to add a test case for that.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
I was bitten by this very same case once. Thanks!

**Comment by mosteo** [comment]
Minor last thing: I would move the test from the `get` to the `config` dir, as it applies outside of the get command.

**Comment by mosteo** [comment]
Thanks, merged.

**Pull request merged**
