### PR TITLE
Fixes for CE2021.

### PR DESCRIPTION
**Pull request by simonjwright**
Remove compilation warnings from GNAT CE 2021.

### CODE REVIEW

**Comment by simonjwright** [comment]
Not sure how to deal with this!

CE2021 thinks e.g. `Alire.Utils.Append_Vector` **is** overriding, and without `overriding` gives a *style check* warning.

CE2020 thinks it’s **not** overriding, and gives an error with `overriding`.

*Is* it overriding?

Can I do
```
   pragma Style_Checks (Off);  -- for GNAT CE 2021, wants 'overriding'
   procedure Append_Vector (V : in out String_Vector; V2 : String_Vector)
                            renames Append;
   pragma Style_Checks (On);
```

NB, the same happens with `AAA.Strings.Append_Vector` .... ah! I see it’s gone in the devel branch!

**Comment by simonjwright** [comment]
Oh yes, I saw that warning in GNATColl.JSON.Utilities, but of course that’s in a submodule. What compiler release is arch-rolling running? GCC 11?

**Comment by mosteo** [comment]
Hi Simon, I'm afraid I stepped on your toes with https://github.com/alire-project/alire/pull/746. Indeed the fixes were quite more complex than removing a few unused withs :S. 

You might try to merge that one and see if there are changes in your patch that I missed.

> Is it overriding?

From my research, it looks like the offending subprogram was added to the standard library in the 2020 -> 2021 jump, so it was indeed not overriding before, but it is now. For some reason, silencing the warnings was not working (I tried that too). Fortunately we weren't using that anywhere/anymore, so I simply removed it.

Also there were misleading errors as some of our setup actions were downloading the master branch to build, which in effect caused a egg-and-chicken problem.

**Comment by simonjwright** [comment]
Hi Alejandro,

Aside from removing the possibly-overriding subprogram, and a newline that you'd inserted & I hadn't, the merge was clean. Like Minds!

It also builds cleanly with FSF GCC 11.1.0 (I have a linking issue, but that's me, not you :-)

**Comment by mosteo** [comment]
Hi @simonjwright , do you plan to do something more in this PR, or is it safe to close?

**Comment by simonjwright** [comment]
Everything I wanted to do is done .. closing.

**Pull request closed without merging**
