### PR TITLE
Disallow dots in identifiers

### LINKED ISSUE #1076: Disallow identifiers starting with dots
I noticed that it is possible to create a crate with a name starting with `.`:
```shell
$ alr init --bin .dot    
Alire needs some user information to initialize the crate author and maintainer,
...
✓ .dot initialized successfully.
$ cd .dot 
$ alr printenv       
ⓘ Synchronizing workspace...
Nothing to update.                                                       

export .DOT_ALIRE_PREFIX="/tmp/.dot"
export ALIRE="True"
...
```
This leads to an error when trying to export the environment:
```shell
$ eval $(alr printenv)
export: not valid in this context: .DOT_ALIRE_PREFIX
```

Looking at https://github.com/alire-project/alire/pull/350 and that leading underscores are disallowed I suppose this is unintended behaviour.

### PR DESCRIPTION
**Pull request by 0rzech**
Fixes #1076.

### CODE REVIEW

**Review by Fabien-Chouteau — APPROVED** [review]

**Comment by Fabien-Chouteau** [comment]
@mosteo I didn't know we still allowed dots in crate names.

**Comment by mosteo** [comment]
This must have slipped through the cracks; it was certainly unintended at this point.

**Comment by mosteo** [comment]
So the proper patch would be to remove these extension separator remains in `alire.ads`, not to document it, sorry @0rzech.

I'm quite surprised this has gone unnoticed for so long.

**Comment by 0rzech** [comment]
@mosteo No problemo. 😉 I've removed dot support in crate names completely.

**Comment by 0rzech** [comment]
@mosteo No problemo. 😉 I've removed dot support in identifiers completely. This removes dot support in index names too. Not sure you want that as well.

**Comment by 0rzech** [comment]
@mosteo No problemo. 😉 I've removed support for dots in identifiers completely. This affects index names too. I'm not sure if we want that as well, though.

**Review by Fabien-Chouteau — APPROVED** [review]

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Thanks for the patience, @0rzech

**Pull request merged**
