### PR TITLE
Merge AEP-2-derived changes to manifests into master

### PR DESCRIPTION
**Pull request by mosteo**
Once merged:
- [x] Make `devel-0.4` the default branch for `alire-index`

### CODE REVIEW

**Comment by mosteo** [comment]
This one bring in all the changes of late that were kept separate as most are breaking, so we only have one big break for our users.

I wonder if we should have some mitigation measure to help our current users. We could autodetect a manifest in the old location and stop with an explanation instead of erroring with the generic "cannot continue with invalid session"...

**Comment by Fabien-Chouteau** [comment]
> I wonder if we should have some mitigation measure to help our current users. We could autodetect a manifest in the old location and stop with an explanation instead of erroring with the generic "cannot continue with invalid session"...

It doesn't sound too hard to do.

**Comment by mosteo** [comment]
> It doesn't sound too hard to do.

Right, so I'll get on it.

**Review by Fabien-Chouteau — APPROVED** [review]

**Comment by Fabien-Chouteau** [comment]
:partying_face: That is a huge milestone. Congrats @mosteo

**Pull request merged**
