### PR TITLE
Do not allow old-style licenses in strict index mode

### PR DESCRIPTION
**Pull request by mosteo**

### CODE REVIEW

**Review by Fabien-Chouteau — APPROVED** [review]
Do we have a test for "strict loading"?

**Comment by mosteo** [comment]
> Do we have a test for "strict loading"?

I think so, but I'll double check because my memory...

**Comment by mosteo** [comment]
There's `tests/index/check_enums`. BTW, ~local~ working folder manifests are always loaded in strict mode.

**Comment by mosteo** [comment]
On second thought I don't think this is worth the hassle. After 1.2 is out we can simply remove the old license format and be done with it.

**Pull request closed without merging**
