### PR TITLE
Roots: retrieve GPR files from solution releases

### PR DESCRIPTION
**Pull request by mosteo**
@Fabien-Chouteau let me know if this is what you need. (It's untested so it may need tweaking.)

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Thank you @mosteo, I don't think this is what I need.
I want to create a gpr config file for each release of a solution. And for each of the files I need the project files of the direct dependencies of that release.

The calling code will look something like that: 
```ada
     for Rel of Solution.Releases.Including (Root.Release) loop
        declare
           List_Of_Withs : ........ := Solution.Get_Direct_Withs (Rel);
        begin
           This.Generate_GPR_Config  (Rel.Name, "config.gpr", List_Of_Withs);
        end;
      end loop;
```

`Solution.Get_Direct_Withs` would return the list of direct "withs" for the given release.

**Comment by mosteo** [comment]
OK, now I understand

**Comment by mosteo** [comment]
Fabien, check the new `Alire.Roots.Direct_Withs` function.

**Comment by Fabien-Chouteau** [comment]
That works, thank @mosteo

**Pull request closed without merging**
