### PR TITLE
Check for required tools and install from distro

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
If there is a known distro, and the tool is available, and the user agrees.

This PR is based on the msys2 support PR #336.

Ref #338

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
The Windows check fails because a `tar` exec is already install but it doesn't work for some reason...

**Review by mosteo — APPROVED** [review]
Very nice. I don't think I can readily help with the test failures, but do tell me if there's something you want me to do.

**Comment by Fabien-Chouteau** [comment]
> Very nice. I don't think I can readily help with the test failures, but do tell me if there's something you want me to do.

I already saw this problem with the `tar` available in the GitHub Action environment. Maybe I should force the install of msys2's `tar`.

**Comment by Fabien-Chouteau** [comment]
That worked. 

@mosteo ready when you are.

**Comment by mosteo** [comment]
Merged, thanks!

**Comment by Fabien-Chouteau** [comment]
Thank you @mosteo, I opened #347 for `master` because this PR was to merge on the msys2 branch.

**Comment by mosteo** [comment]
I saw it too late, and I should have changed the base branch. Something to remember next time :+1:

**Pull request merged**
