### PR TITLE
Change jekyll output to use the long description

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Fails because of #308.

**Review by mosteo — APPROVED** [review]

**Comment by Fabien-Chouteau** [comment]
@mosteo if you can merge this one today that would be nice. I am improving the website at the same time.

**Comment by Fabien-Chouteau** [comment]
Thank you :)

**Comment by mosteo** [comment]
Sure, sorry for the delay. Do you want #301 to go in before FOSDEM too?

**Comment by Fabien-Chouteau** [comment]
> Sure, sorry for the delay. Do you want #301 to go in before FOSDEM too?

Yes, I think it's better because my embedded project won't build cleanly without it.

**Comment by mosteo** [comment]
OK!

**Pull request merged**
