### PR TITLE
Improve user experience with better manifest errors messages

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
This is patch introduces suggestions in various error messages from the manifest parser. A potential suggestion is made using edit distance computing from a list of possible values. If the quality is not deemed good enough, the full list of values is printed.

### CODE REVIEW

**Comment by mosteo** [comment]
Very cool!

**Comment by Fabien-Chouteau** [comment]
@mosteo somethings wrong with the macOS CI. I don't think they updated the `macos-latest` version. Maybe it's GNAT 12.2...

**Comment by mosteo** [comment]
I see... Strange, and different in each macOS setup. No immediate ideas to offer :/

**Comment by Fabien-Chouteau** [comment]
@simonjwright we have some issues on macOS that I don't understand, in case you have some time to give it a look.

**Comment by simonjwright** [comment]
I can find the tests, and I can run them locally, and I see failures. What I _can’t_ see is how to run an individual test in diagnostic mode (i.e. so I can see what went wrong in detail).

**Comment by Fabien-Chouteau** [comment]
`-v -E` for more detailed output and path to folder to filter tests e.g. `tests/misc/did-you-mean`

So `./run.py -v -E tests/misc/did-you-mean`

**Comment by simonjwright** [comment]
Here are the tests which failed when run together from the top level.
### publish__check-pre-release-version
PASS
### publish__local-repo
FAIL
_Output: 
_Initialized empty Git repository in /private/var/folders/_q/fvnxz46903z9hjh38fz0lyhm0000gs/T/tmpzy5hjtqu/publish__local-repo/xxx/.git/
_[main (root-commit) 915db17] repo created
_ 9 files changed, 134 insertions(+)
_ create mode 100644 .gitignore
_ create mode 100644 alire.toml
_ create mode 100644 alire/alire.lock
_ create mode 100644 alire/config.toml
_ create mode 100644 config/xxx_config.ads
_ create mode 100644 config/xxx_config.gpr
_ create mode 100644 config/xxx_config.h
_ create mode 100644 src/xxx.adb
_ create mode 100644 xxx.gpr
_Cloning into 'xxx_local'...
_done.
_The following command:
_  alr -q -d -n --force publish . master
_Exitted with status code 1
_Output:
_stderr: Command ["git", "log", "master", "-n1", "--oneline", "--no-abbrev-commit"] exited with code 128 and output: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'
_stderr: Revision not found in local repository: master
_ERROR: Revision not found in local repository: master
_
_Traceback (most recent call last):
_  File "/private/var/folders/_q/fvnxz46903z9hjh38fz0lyhm0000gs/T/tmpzy5hjtqu/publish__local-repo/test.py", line 40, in <module>
_    run_alr("--force", "publish", ".", "master")
_  File "/Users/simon/Developer/alire/testsuite/drivers/alr.py", line 112, in run_alr
_    raise CalledProcessError('alr returned non-zero status code')
_drivers.alr.CalledProcessError: alr returned non-zero status code
### misc__did-you-mean 
PASS
### publish__local-repo-nonstd 
FAIL
_Initialized empty Git repository in /private/var/folders/_q/fvnxz46903z9hjh38fz0lyhm0000gs/T/tmp_g19jvr1/publish__local-repo-nonstd/xxx/.git/
_[main (root-commit) 60ca0f5] repo created
_ 9 files changed, 134 insertions(+)
_ create mode 100644 .gitignore
_ create mode 100644 alire/alire.lock
_ create mode 100644 alire/config.toml
_ create mode 100644 config/xxx_config.ads
_ create mode 100644 config/xxx_config.gpr
_ create mode 100644 config/xxx_config.h
_ create mode 100644 src/xxx.adb
_ create mode 100644 xxx.gpr
_ create mode 100644 xxx.toml
_Cloning into 'xxx_local'...
_done.
_The following command:
_  alr -q -d -n --force publish . master --manifest xxx.toml
_Exitted with status code 1
_Output:
_stderr: Command ["git", "log", "master", "-n1", "--oneline", "--no-abbrev-commit"] exited with code 128 and output: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'
_stderr: Revision not found in local repository: master
_ERROR: Revision not found in local repository: master
_
_Traceback (most recent call last):
_  File "/private/var/folders/_q/fvnxz46903z9hjh38fz0lyhm0000gs/T/tmp_g19jvr1/publish__local-repo-nonstd/test.py", line 42, in <module>
_    run_alr("--force", "publish", ".", "master", "--manifest", "xxx.toml")
_  File "/Users/simon/Developer/alire/testsuite/drivers/alr.py", line 112, in run_alr
_    raise CalledProcessError('alr returned non-zero status code')
_drivers.alr.CalledProcessError: alr returned non-zero status code
### index__branch-mismatch
FAIL
_Traceback (most recent call last):
_  File "/private/var/folders/_q/fvnxz46903z9hjh38fz0lyhm0000gs/T/tmp18xmgrcf/index__branch-mismatch/test.py", line 35, in <module>
_    assert_match(".*This alr build expects an index branch with prefix '.*'"
_  File "/Users/simon/Developer/alire/testsuite/drivers/asserts.py", line 61, in assert_match
_    assert False, '\n'.join(text)
_AssertionError: Unexpected output
_Expecting a match on:
_  ".*This alr build expects an index branch with prefix '.*' but your community index branch is 'master'.*"
_But got:
_  "warning: This alr build expects an index branch with prefix 'stable' but your community index branch is 'main'"
_  "warning: You can disable this warning with configuration key 'warning.old_index'"
_  "warning: Index 'community' version (1.1.0) is older than the newest supported by alr (1.2.1)"
_  "warning: You can disable this warning with configuration key 'warning.old_index'"
_  "Note: If you experience any problems loading this index, you may need to reset the community index with 'alr index --reset-community'. Note that this operation will delete any local changes to the community index."
_  'No hits'
### misc__local-reject-origin
PASS
### build_profile__default
PASS

**Comment by Fabien-Chouteau** [comment]
Looks like you don't have the same errors as we have on the GitHub CI.

**Comment by simonjwright** [comment]
My trouble seems to be that I’m running git version 2.37.0 (Apple Git-136) which defaults the initial branch to `main`, so that’s what `helpers.py/init_git_repo()` does; and the tests expect the branch to be `master`.

**Comment by mosteo** [comment]
> the tests expect the branch to be master

Ohhh well spotted.

**Comment by simonjwright** [comment]
I’m getting a PR together. Running CI in my repo now.

**Comment by simonjwright** [comment]
Gosh it’s slow! the macos runner took 1h7m to install the toolchain, and has already spent an hour in _Run test script (without Homebrew)_ and is still compiling `alire-releases.adb`.

**Comment by simonjwright** [comment]
I spoke too soon. See PR #1244.

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
So by merging this we are going temporarily with the old macOS version, right? At least it buys us some time.

**Pull request merged**
